/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelDate } from './modelDate';
/**
 * API auth token
 */
export interface AuthToken {
    /**
     * Auth token uuid
     */
    id: string;
    /**
     * User
     */
    user_id: string;
    /**
     * Name of token
     */
    name: string;
    /**
     * When the token expires
     */
    expiry_at?: string;
    /**
     * Combined token required for requesting an access token, this field is only returned once on creation or update (during regeneration).
     */
    token?: string;
    date: ModelDate;
}
