/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Scaling logic
 */
export interface FunctionScaling {
    /**
     * CPU or Memory supported
     */
    type: FunctionScaling.TypeEnum;
    /**
     * For type to drop below before scale down
     */
    low: number;
    /**
     * For type to go above before scale up
     */
    high: number;
}
export declare namespace FunctionScaling {
    type TypeEnum = 'cpu' | 'memory';
    const TypeEnum: {
        cpu: TypeEnum;
        memory: TypeEnum;
    };
}
