/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Counter (monotonically incrementing)
 */
export interface MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter {
    /**
     * Average counter value
     */
    avg?: number | null;
    /**
     * Number of counter values
     */
    count?: number | null;
    /**
     * Maximum counter value
     */
    max?: number | null;
    /**
     * Minimum counter value
     */
    min?: number | null;
    /**
     * Sum of counter values
     */
    sum?: number | null;
}
