/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetricHttpAggregationHttpCodesBucketsInner } from './metricHttpAggregationHttpCodesBucketsInner';
/**
 * HTTP status code aggregation
 */
export interface MetricHttpAggregationHttpCodes {
    /**
     * Array of unique http status codes
     */
    buckets?: Array<MetricHttpAggregationHttpCodesBucketsInner>;
    /**
     * Upper bound of error in document count
     */
    doc_count_error_upper_bound?: number;
    /**
     * Sum of other document counts
     */
    sum_other_doc_count?: number;
}
