/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { ListLogResponse } from '../model/models';
import { LogsListFTimestampsParameter } from '../model/models';
import { OrganisationsListPageParameter } from '../model/models';
import { Configuration } from '../configuration';
export interface LogsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    /**
     * Get logs
     * Retrieve logs for a specific project or function. Use the query parameter to search logs.  &gt; Note: Logs are always returned in a descending order based on the timestamp. &gt; Note: A max size of 500 logs is returned per request (when using page[size]).
     * @param page Query parameters for pagination
     * @param f_project Project uuid reference
     * @param f_function Function uuid reference
     * @param f_timestamps Timestamp restriction for query
     * @param f_query Text query string
     * @param f_log_type Type of log
     */
    logsList(page?: OrganisationsListPageParameter, f_project?: string, f_function?: string, f_timestamps?: LogsListFTimestampsParameter, f_query?: string, f_log_type?: 'info' | 'error', extraHttpRequestParams?: any): Observable<ListLogResponse>;
}
