/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DeletedResponse } from '../model/models';
import { ListOrganisationResponse } from '../model/models';
import { OrganisationBody } from '../model/models';
import { OrganisationResponse } from '../model/models';
import { OrganisationsListPageParameter } from '../model/models';
import { Configuration } from '../configuration';
export interface OrganisationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    /**
     * Create organisations
     * Create an organisation
     * @param OrganisationBody Create/Update any field
     */
    organisationsCreate(OrganisationBody?: OrganisationBody, extraHttpRequestParams?: any): Observable<OrganisationResponse>;
    /**
     * Delete an organisation
     * Delete organisation, this will also delete all the resources within the organisation
     * @param organisation_id Organisation ID reference
     */
    organisationsDelete(organisation_id: string, extraHttpRequestParams?: any): Observable<DeletedResponse>;
    /**
     * Get an organisation
     * Get a single organisation
     * @param organisation_id Organisation ID reference
     */
    organisationsGet(organisation_id: string, extraHttpRequestParams?: any): Observable<OrganisationResponse>;
    /**
     * List organisations
     * List organisations
     * @param page Query parameters for pagination
     * @param f_name Filter resource on name, if the value ends in an asterix it will be treated as a partial search otherwise, it\&#39;ll be an exact match
     */
    organisationsList(page?: OrganisationsListPageParameter, f_name?: string, extraHttpRequestParams?: any): Observable<ListOrganisationResponse>;
    /**
     * Update an organisation
     * Update an organisation
     * @param organisation_id Organisation ID reference
     * @param OrganisationBody Create/Update any field
     */
    organisationsUpdate(organisation_id: string, OrganisationBody?: OrganisationBody, extraHttpRequestParams?: any): Observable<OrganisationResponse>;
}
