/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { ProviderInner } from '../model/models';
import { Configuration } from '../configuration';
export interface ProvidersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    /**
     * Get available providers
     * Retrieve a list of all providers with their respective deployed regions and cities.
     */
    providersGet(extraHttpRequestParams?: any): Observable<Array<ProviderInner>>;
}
